apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: saleor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
            - containerPort: 16686
            - containerPort: 14268
            - containerPort: 9411
          volumeMounts:
            - mountPath: /tmp
              name: tmpfs-volume
          resources:
            requests:
              memory: "500Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "200m"
      volumes:
        - name: tmpfs-volume
          emptyDir:
            medium: "Memory"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
  namespace: saleor
spec:
  selector:
    app: jaeger
  ports:
    - name: agent-udp
      protocol: UDP
      port: 5775
      targetPort: 5775
    - name: collector-udp
      protocol: UDP
      port: 6831
      targetPort: 6831
    - name: collector-tchannel-udp
      protocol: UDP
      port: 6832
      targetPort: 6832
    - name: admin
      protocol: TCP
      port: 5778
      targetPort: 5778
    - name: query
      protocol: TCP
      port: 16686
      targetPort: 16686
    - name: collector-http
      protocol: TCP
      port: 14268
      targetPort: 14268
    - name: zipkin
      protocol: TCP
      port: 9411
      targetPort: 9411
  type: ClusterIP

