apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: saleor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/saleor/saleor:3.20
          command: [ "celery", "-A", "saleor", "--app=saleor.celeryconf:app", "worker", "--loglevel=info", "-B" ]
          envFrom:
            - configMapRef:
                name: common-env
            - configMapRef:
                name: backend-env
          resources:
            requests:
              memory: "100Mi"
              cpu: "75m"
            limits:
              memory: "200Mi"
              cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: worker-service
  namespace: saleor
spec:
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-env
data:
  CELERY_BROKER_URL: "redis://saleor-redis-service:6379/1"
  DATABASE_URL: "postgres://saleor:saleor@saleor-db-service/saleor"
  DEFAULT_FROM_EMAIL: "noreply@example.com"
  EMAIL_URL: "smtp://mailpit-service:1025"
  SECRET_KEY: "changeme"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-env
data:
  DEFAULT_CHANNEL_SLUG: "default-channel"
  HTTP_IP_FILTER_ALLOW_LOOPBACK_IPS: "True"
  HTTP_IP_FILTER_ENABLED: "True"

